apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign-deployment
spec:
  replicas:1
  selector:
    matchlabels:
      app: jivedh2019/assign
  template:
    metadata:
      name: Jivedh2019
      labels:
        app: jivedh2019/assign
    spec:
      containers:
      - name: my-container
        image: jivedh2019/assign:7
        ports:
        - containerPort: 80
